version: "2"
services:
  boxfuse-sample-java-war-hello:
    build: .
    links:
      - tomcat
  tomcat:
    image: tomcat:9.0-jre8-alpine
    volumes:
      - "./target:/usr/local/tomcat/webapps/"
    ports:
      - "8080:8080"
    entrypoint:
      - "catalina.sh"
      - "run"
