version: "3"
volumes:
  web_data:
    external: true
services:
  boxfuse-sample-java-war-hello:
    build: .
    volumes:
      - web_data:/tmp/target/
  tomcat:
    image: tomcat:9.0-jre8-alpine
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/web_data/_data
        target: /usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    entrypoint:
      - "catalina.sh"
      - "run"
